- name: "Configure Device"
  hosts: localhost
  vars:
    ansible_user: "{{ user }}"
    ansible_password: "{{ pass }}"
  connection: local
  gather_facts: yes
  tasks:
    - name: "Change root password"
      juniper.device.config:
        config_mode: "private"
        load: "set"
        lines:
          - "set system root-authentication encrypted-password {{ encrypted_password }}"
      register: response

    - name: "Print the config changes"
      debug:
        var: response.changed